server:
  port: 0

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
          batch_size: 20
        generate_statistics: false
    show-sql: true
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2_auth_db
    username: h2
    password: 123
  h2:
    console:
      enabled: true
      path: /h2console/
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
